format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
${env_var.vaulta}\
$jobs\
$cmd_duration\
$status\
$line_break\
[\uf054](bright-black) \
"""

[username]
style_root = "red"
style_user = "bright-black"
format = "[$user]($style) "
detect_env_vars = ['!TMUX']

[hostname]
ssh_only = false
format = "[\uf1fa](blue) [$hostname](bright-black) "
detect_env_vars = ['!TMUX', 'SSH_CONNECTION', 'MOBILEHOME']

[directory]
format = "[$path](blue)[$read_only](red)"
fish_style_pwd_dir_length = 1
truncate_to_repo = true
truncation_length = 1
read_only = " \uf023"

[git_branch]
only_attached = true
format = " [\ue0b6](black)[\ueafc](blue bg:black)[ $branch](bg:black)"

[git_commit]
tag_disabled = false
format = " [\ue0b6](black)[\ueabc](blue bg:black)[ $hash](bg:black)[$tag](bg:black dimmed)"
tag_symbol = "#"

[git_status]
format = "[$stashed$ahead_behind$conflicted$staged$modified$untracked](bg:black)[\ue0b4](black)"
stashed = " [\uf192](white bg:black)"
ahead = " [\uf139](blue bg:black)"
behind = " [\uf13a](blue bg:black)"
diverged = " [\uf057](purple bg:black)"
conflicted = " [\uf06a](red bg:black)"
staged = " [\uf111](green bg:black)"
modified = " [\ueabc](yellow bg:black)"
untracked = " [\uf059](bright-black bg:black)"

[env_var.vaulta]
variable = "VAULTA"
format = " [\ue0b6](black)[\uf132](blue bg:black)[ $env_value](bg:black)[\ue0b4](black)"

[jobs]
number_threshold = 1
format = " [\ue0b6](black)[\ueabc](blue bg:black)[ $number](bg:black)[\ue0b4](black)"

[cmd_duration]
format = " [\ue0b6](black)[\uf2f2](blue bg:black)[ $duration](bg:black)[\ue0b4](black)"
min_time = 3_000

[status]
disabled = false
format = " [\ue0b6](black)[\uf06a](red bg:black)[ $maybe_int$common_meaning$signal_name](bg:black)[\ue0b4](black)"

[fill]
symbol = " "
