format = """
 $username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$jobs\
$cmd_duration\
$status\
$character\
$time\
$line_break \
[\uf054](green) \
"""

[username]
style_root = "red"
style_user = "bright-black"
format = "[$user]($style) "

[hostname]
format = "[\uf564](blue) [$hostname](bright-black) "

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = true
truncation_length = 1
style = "blue"
read_only = " \uf840"

[git_branch]
format = "[$branch](bright-black) "

[git_commit]
format = "[$hash$tag](bright-black) "

[git_status]
format = "$stashed$ahead_behind$conflicted$staged$modified$untracked"
stashed = "[\uf187](white) "
ahead = "[\uf077](bright-blue) "
behind = "[\uf078](bright-blue) "
diverged = "[\ufc09](bright-purple) "
conflicted = "[\uf06a](red) "
staged = "[\uf111](green) "
modified = "[\uf10c](yellow) "
untracked = "[\uf29c](bright-black) "

[fill]
symbol = " "

[jobs]
format = "[\uf79f](bright-blue) "

[cmd_duration]
format = "[$duration](bright-black) "

[status]
disabled = false
format = "[($signal_name )$status](red) "

[character]
success_symbol = "[\uf111](green)"
error_symbol = "[\uf111](red)"

[time]
disabled = false
format = "[$time](bright-black)"
